# Generated by Django 4.1.7 on 2023-06-23 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0024_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='customer',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
