# Generated by Django 4.1.7 on 2023-06-24 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0025_cart_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='userS',
        ),
    ]
